name: CI

on:
  # mainブランチへのpush / Actionsページからボタンで起動
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment
        run: |
          echo "event_name| ${{ github.event_name }}"
          echo 'OS| ${{ runner.os }}'
          echo "repo| ${{ github.repository }}."
          echo "branch| ${{ github.ref }}"
          echo "checkout dir| ${{ github.workspace }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install papermill
        run: |
          python3 --version
          pip3 --version
          pip3 install jupyterlab papermill
      - name: Run Script
        run: |
          cd ${{ github.workspace }}/tools
          papermill --log-output make-zip.ipynb tmp/tmp.ipynb
      - run: echo "exit status| ${{ job.status }}"
