name: CI

on:
  # mainブランチへのpush / Actionsページからボタンで起動
  push:
    branches: 
      - main
  workflow_dispatch:

env:
  # SlackApp の WebHook URL
  # CI結果のSlack報告用
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  job-01:
    runs-on: ubuntu-latest
    steps:

    - name: Check Environment
      run: |
        pwd
        echo "event_name| ${{ github.event_name }}"
        echo 'OS| ${{ runner.os }}'
        echo "repo| ${{ github.repository }}."
        echo "branch| ${{ github.ref }}"
        echo "checkout dir| ${{ github.workspace }}"

    - name: Checkout main repo
      uses: actions/checkout@v3
      with:
        path: main
        ref: main

    - name: Checkout gh-pages repo
      uses: actions/checkout@v3
      with:
        path: gh-pages
        ref: gh-pages

    - name: Install Requirements
      run: |
        pwd
        python3 --version
        pip3 --version
        pip3 install -r requirements.txt
      working-directory: main/tools

    - name: Run Script
      run: |
        pwd
        papermill --log-output make-zip.ipynb tmp/tmp.ipynb
        mv tmp/test.zip ../../gh-pages/docs/
      working-directory: main/tools

    - name: Commit gh-pages files
      uses: EndBug/add-and-commit@v9
      with:
        cwd: gh-pages
        add: '.'
        author_name: 'github-actions'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'update test.zip'
        push: true

    - run: echo "exit status| ${{ job.status }}"

    # 成功
    - name: Success
      if: success()
      uses: rtCamp/action-slack-notify@v2.0.2
      env:
        SLACK_CHANNEL: practice-badges-ci
        SLACK_TITLE: CI処理成功
        SLACK_COLOR: good

    # 失敗
    - name: Failure
      uses: rtCamp/action-slack-notify@v2.0.2
      if: failure()
      env:
        SLACK_CHANNEL: practice-badges-ci
        SLACK_TITLE: CI処理失敗
        SLACK_COLOR: danger
